services:
    louvre_louvre.booking:
        class: Louvre\LouvreBundle\Services\BookingService
    louvre_louvre.validNumber:
        class: Louvre\LouvreBundle\Services\ValidNumberService
        arguments: ['@doctrine.orm.entity_manager']
