parameters:
    stripe_public_key: sk_test_qAyRDTaNGJTzEnxhPHrBsvm1
    normal: 16
    enfant: 8
    reduit: 10
    senior: 12
    maxtickets: 1000


services:
    louvre_louvre.booking:
        class: Louvre\LouvreBundle\Services\BookingService
        arguments: ['@mailer','@templating', '@louvre_louvre.calcul_age', '%normal%', '%enfant%', '%reduit%', '%senior%']
    louvre_louvre.validNumber:
        class: Louvre\LouvreBundle\Services\ValidNumberService
        arguments: ['@doctrine.orm.entity_manager', '%maxtickets%']
    louvre_louvre.stripe:
        class: Louvre\LouvreBundle\Services\StripeService
        arguments: ['%stripe_public_key%']
    louvre_louvre.calcul_age:
        class: Louvre\LouvreBundle\Services\CalculAge