parameters:
    stripe_public_key: pk_test_YyJYkgu1VfUxiveZoEb4Ru3z

services:
    louvre_louvre.booking:
        class: Louvre\LouvreBundle\Services\BookingService
        arguments: ['@mailer','@templating', '@louvre_louvre.calcul_age']
    louvre_louvre.validNumber:
        class: Louvre\LouvreBundle\Services\ValidNumberService
        arguments: ['@doctrine.orm.entity_manager']
    louvre_louvre.stripe:
        class: Louvre\LouvreBundle\Services\StripeService
        arguments: ['%stripe_public_key%']
    louvre_louvre.calcul_age:
        class: Louvre\LouvreBundle\Services\CalculAge